### ISSUE TITLE
Question: Can you use communicate with both the server and client as netty-zmtp?

### ISSUE THREAD

**Issue by vshank77** [spotify/netty-zmtp#14]
My server pipeline looks like below:

        serverBootstrap = new ServerBootstrap(new NioServerSocketChannelFactory(
                newCachedThreadPool(), newCachedThreadPool()));
        serverBootstrap.setPipelineFactory(new ChannelPipelineFactory() {
            private final Executor executor = new OrderedMemoryAwareThreadPoolExecutor(
                    getRuntime().availableProcessors(), 1024 * 1024, 128 * 1024 * 1024);

            public ChannelPipeline getPipeline() throws Exception {
                return Channels.pipeline(new ExecutionHandler(executor), new ZMTP20Codec(new ZMTPSession(
                        Addressed, 1024, null, ROUTER), false), new ServerHandler());
            }
        });

My Client pipeline looks below:

        clientBootstrap = new ClientBootstrap(new NioClientSocketChannelFactory(
                newCachedThreadPool(), newCachedThreadPool()));
        clientBootstrap.setPipelineFactory(new ChannelPipelineFactory() {
            public ChannelPipeline getPipeline() throws Exception {
                return Channels.pipeline(new ZMTP20Codec(new ZMTPSession(Addressed, 1024), false),
                        new OneToOneDecoder() {
                            @Override
                            protected Object decode(ChannelHandlerContext ctx, Channel channel, Object msg)
                                    throws Exception {
                                System.out.println(msg);
                                return null;
                            }
                        });
            }
        });

However if I try to send a message to server, I get the following exception

     Caused by: java.lang.IllegalArgumentException: unsupported message type: class com.spotify.netty.handler.codec.zmtp.ZMTPMessage
    	at org.jboss.netty.channel.socket.nio.SocketSendBufferPool.acquire(SocketSendBufferPool.java:52)
    	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:193)
    	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromTaskLoop(AbstractNioWorker.java:151)
    	at org.jboss.netty.channel.socket.nio.AbstractNioChannel$WriteTask.run(AbstractNioChannel.java:335)
    	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:372)
    	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:296)
    	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
    	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    	at java.lang.Thread.run(Thread.java:744)

Can you please help?

**Comment by danielnorberg** [comment]
Here's an end to end test:

https://github.com/spotify/netty-zmtp/blob/master/src/test/java/com/spotify/netty4/handler/codec/zmtp/EndToEndTest.java
